import type { ArchiveConfig, ArchiveTask } from './types'

export const taskDefaults: ArchiveTask = {
  id: '',
  name: '新建归档任务',
  batch_name_template: '{date}_{sequence}',
  archive_name_template: '{id}',
  archive_layout: 'directory',
  enabled: false,
  source_dir: '',
  output_dir: '',
  manifest_dir: '',
  cron: '0 2 * * *',
  timezone: '',
  recursive: true,
  include_patterns: [],
  exclude_patterns: [],
  grouping: 'directory_date',
  directory_depth: 1,
  time_grain: 'day',
  max_files: 1000,
  max_bytes: 4294967296,
  max_batches: 10,
  archive_age_days: 7,
  stability_seconds: 60,
  auto_continue: false,
  max_pending_archives: 1,
  max_pending_bytes: 0,
  min_free_bytes: 1073741824,
  format: '7z',
  compression: 'normal',
  encryption: 'none',
  encrypt_names: false,
  password: '',
  password_version: '1',
  verify: true,
  delete_source: false,
}

export const configDefaults: ArchiveConfig = {
  enabled: false,
  notify: false,
  notify_events: ['failure'],
  tasks: [],
}
