name: PR-Agent

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - review_requested
      - synchronize
  issue_comment:
    types:
      - created
      - edited

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pr-agent:
    if: >-
      github.event.sender.type != 'Bot' &&
      (
        (
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          github.event.pull_request.user.login == github.repository_owner &&
          github.actor == github.repository_owner
        ) ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request != null &&
          contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR", "CONTRIBUTOR", "FIRST_TIME_CONTRIBUTOR"]'), github.event.comment.author_association)
        )
      )
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.issue.number }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Run PR Review
        uses: docker://ghcr.io/infinitypacer/pr-review-runner:0.0.1@sha256:08683a59dc210dca9f4f7e444d4578cad0ad9fb5cac498b23293a5647e2e51ce
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI.API_BASE: ${{ secrets.OPENAI_API_BASE }}
          PRR_AUTO_REVIEW_SCOPE: all
          PRR_ALLOWED_ASSOCIATIONS: '["OWNER", "MEMBER", "COLLABORATOR", "CONTRIBUTOR", "FIRST_TIME_CONTRIBUTOR"]'
          PRR_DISABLED_COMMANDS: '["/improve"]'
          PRR_SKIP_LABEL: skip pr-agent
          PRR_SKIP_TITLE_PATTERN: '^(?:\[Auto\]|Auto)'
          config.response_language: zh-CN
